name: Dev Container

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 81
            php-str: 8.1
          - php: 82
            php-str: 8.2
          - php: 83
            php-str: 8.3
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        env:
          PHP_VERSION: ${{ matrix.php }}
          PHP_VERSION_STR: ${{ matrix.php-str }}
        with:
          subFolder: src-devc
          imageName: opencodeco/phpctl
          imageTag: php${{ matrix.php }}-devcontainer
          push: always
